# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# VM for development on ESP devices 
# Includes libs for ESP12 and ESP32

SF="~/."
ARDUINO_VERS="1.8.10"

# Install stuff - esp tool and Visual Studio Code
$script_installsw = <<SCRIPT
apt-get update
apt-get -y install python-pip
pip install esptool

wget --progress=bar:force -O vscode.deb https://go.microsoft.com/fwlink/?LinkID=760868
dpkg -i vscode.deb
rm vscode.deb
SCRIPT


# Install ESP and Arduino utils
$script_installarduino = <<SCRIPT

wget --progress=bar:force http://downloads.arduino.cc/arduino-#{ARDUINO_VERS}-linux64.tar.xz
tar xvf -C ~/Downloads
rm arduino-#{ARDUINO_VERS}-linux64.tar.xz

ln -s ~/Downloads/arduino-#{ARDUINO_VERS}/arduino ~/Desktop/Arduino

~/Desktop/Arduino --pref \\"boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json,http://arduino.esp8266.com/stable/package_esp8266com_index.json\\" --save-prefs

~/Desktop/Arduino --install-boards esp32:esp32 --save-prefs
~/Desktop/Arduino --install-boards esp8266:esp8266 --save-prefs

~/Desktop/Arduino --install-library \\"ArduinoJson\\"
~/Desktop/Arduino --install-library \\"Adafruit Unified Sensor\\"
~/Desktop/Arduino --install-library \\"Adafruit BMP280 Library\\"
~/Desktop/Arduino --install-library \\"DHT sensor library\\"
~/Desktop/Arduino --install-library \\"M5Stack\\"
~/Desktop/Arduino --install-library \\"MQTT\\"
~/Desktop/Arduino --install-library \\"NTPClient\\"
~/Desktop/Arduino --install-library \\"PubSubClient\\"


code --install-extension vsciot-vscode.vscode-arduino
SCRIPT


Vagrant.configure("2") do |config|

    config.vm.box = "axcxl/debian11_xfce"

    config.vm.provider :virtualbox do |vb|
        vb.gui = true
        vb.memory = 4096
        vb.cpus = 4
    end

    config.vm.define "devesp" do |machine|

        machine.vm.hostname = 'devesp'

        # Install SW
        machine.vm.provision "shell", inline: $script_installsw

        # Install ESP dev tools
        machine.vm.provision "shell", inline: $script_installarduino, privileged: false
    end

    config.vm.synced_folder "#{SF}", "/home/vagrant/workspace", group: "vboxsf", mount_options: ["dmode=775,fmode=664"]

end

