# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# VM for reverse engineering with Ghidra

SF="."

#Install stuff
#NOTE: not sure why java needs ln on Debian 11, but it works
$script_installsw = <<SCRIPT
apt-get update

apt-get -y install binwalk
apt-get -y install bvi

wget --progress=bar:force --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/13+33/5b8a42f3905b406298b72d750b6919f6/jdk-13_linux-x64_bin.deb"
dpkg -i jdk-13_linux-x64_bin.deb
rm jdk-*.deb

ln -s /usr/lib/jvm/jdk-13/bin/* /usr/bin/

DEBIAN_FRONTEND=noninteractive apt-get -y install wireshark
echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections
sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure wireshark-common
addgroup vagrant wireshark
SCRIPT

# Install Ghidra
$script_installgh = <<SCRIPT
wget --progress=bar:force https://ghidra-sre.org/ghidra_9.1-BETA_DEV_20190923.zip
unzip ghidra*.zip -d ~/Downloads
rm ghidra*.zip

ln -s ~/Downloads/ghidra*/ghidraRun ~/Desktop/Ghidra
SCRIPT

Vagrant.configure("2") do |config|

    config.vm.box = "axcxl/debian11_xfce"

    config.vm.provider :virtualbox do |vb|
        vb.gui = true
        vb.memory = 8192
        vb.cpus = 8
    end

    config.vm.define "ghidra" do |machine|

        machine.vm.hostname = 'ghidra'

        # Install SW
        machine.vm.provision "shell", inline: $script_installsw

        # Ghidra
        machine.vm.provision "shell", inline: $script_installgh, privileged: false
    end

    config.vm.synced_folder "#{SF}", "/home/vagrant/workspace"

end

