# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# VM for reverse engineering with Ghidra

VMUSER="dev"
SF="."

#Update the user
$script_updateuser = <<SCRIPT
cp -pr /home/vagrant/.ssh /home/#{VMUSER}/
echo "%#{VMUSER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/#{VMUSER}

addgroup #{VMUSER} tty
addgroup #{VMUSER} dialout
addgroup #{VMUSER} vboxsf
SCRIPT

#Install stuff
$script_installsw = <<SCRIPT
apt-get update
apt-get -y install python3-pip binwalk
apt-get -y install gnome-system-monitor
apt-get -y install bvi
apt-get -y install unzip

wget --progress=bar:force --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/13+33/5b8a42f3905b406298b72d750b6919f6/jdk-13_linux-x64_bin.deb"
dpkg -i jdk-13_linux-x64_bin.deb

wget --progress=bar:force https://ghidra-sre.org/ghidra_9.1-BETA_DEV_20190923.zip -P /home/#{VMUSER}/Downloads
unzip /home/#{VMUSER}/Downloads/ghidra*.zip -d /home/#{VMUSER}
ln -s /home/#{VMUSER}/ghidra*/ghidraRun /home/#{VMUSER}/Desktop/ghidra

chown -R #{VMUSER}:#{VMUSER} /home/#{VMUSER}

DEBIAN_FRONTEND=noninteractive apt-get -y install wireshark
echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections
sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure wireshark-common
addgroup #{VMUSER} wireshark
SCRIPT

Vagrant.configure("2") do |config|

    #Make sure we do not login using the 'vagrant' user
    VAGRANT_COMMAND = ARGV[0]
    if VAGRANT_COMMAND == "ssh"
          config.ssh.username = VMUSER
    end

    config.vm.box = "axcxl/debian9_xfce"

    config.vm.provider :virtualbox do |vb|
        vb.gui = true
        vb.memory = 8192
        vb.cpus = 8
    end

    config.vm.synced_folder "#{SF}", "/home/#{VMUSER}/workspace", group: "vboxsf", owner: "#{VMUSER}"

    config.vm.define "ghidra" do |machine|

        machine.vm.hostname = 'relb'

        # Install SW
        machine.vm.provision "shell", inline: $script_updateuser

        # Install SW
        machine.vm.provision "shell", inline: $script_installsw
    end


end

