# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# VM for working Hexiwear and ZephyrOS 
# How to change the processor and memory at up:
# CPU=2 RAM=4096 vagrant up

# Default values
VMRAM = ENV["RAM"] || "8192"
VMCPU = ENV["CPU"] || "4"

SF="~/workspace"
ZEPHYR_SDK="0.11.3"
S2N="
2010:telnet:600:/dev/ttyACM0:115200 8DATABITS NONE 1STOPBIT banner
2011:telnet:600:/dev/ttyACM1:115200 8DATABITS NONE 1STOPBIT banner
"
S2N_shortcuts="
alias ttyACM0=\"while true; do telnet localhost 2010; sleep 1; done\"
alias ttyACM1=\"while true; do telnet localhost 2011; sleep 1; done\"
"

#Install stuff
$script_installsw = <<SCRIPT
resize2fs /dev/sda1

apt-get update
apt-get -y install python-pip
apt-get -y install ser2net
apt-get -y install --no-install-recommends git cmake ninja-build gperf \
  ccache dfu-util device-tree-compiler wget \
  python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
  make gcc gcc-multilib
SCRIPT

# Install Zephyr DEV ENV
# NOTE: remove the following commands because this should be in the workspace
# To install:
# mkdir zephyrproject somewhere
# git clone zephyr in zephyrproject
# go to zephyrproject -> west init -l zephyr
# still in zephyrproject -> west update
$script_installz = <<SCRIPT

pip install --pre -U pyOCD

pip3 install --user -U west

export PATH=$PATH:/home/vagrant/.local/bin
echo 'export PATH=$PATH:/home/vagrant/.local/bin' >> /home/vagrant/.bashrc

pip3 install --user -r /home/vagrant/workspace/HEXIWEAR/zephyrproject/zephyr/scripts/requirements.txt

wget --progress=bar:force https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v#{ZEPHYR_SDK}/zephyr-sdk-#{ZEPHYR_SDK}-setup.run
chmod u+x zephyr-*.run
./zephyr-sdk-#{ZEPHYR_SDK}-setup.run -- -d ~/zephyr-sdk-#{ZEPHYR_SDK}

echo 'export ZEPHYR_TOOLCHAIN_VARIANT=zephyr' >> /home/vagrant/.bashrc
echo 'export ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk-#{ZEPHYR_SDK}' >> /home/vagrant/.bashrc
SCRIPT

# Update the ser2net config
$script_configser2net = <<SCRIPT
head -n -4 /etc/ser2net.conf > /etc/ser2net.conf.new
mv /etc/ser2net.conf /etc/ser2net.conf.old
mv /etc/ser2net.conf.new /etc/ser2net.conf
echo "#{S2N}" >> /etc/ser2net.conf
service ser2net stop
sleep 1
service ser2net start
SCRIPT


Vagrant.configure("2") do |config|

    config.vm.box = "axcxl/debian11_xfce"
    config.disksize.size = '40GB'

    config.vm.provider :virtualbox do |vb|
        vb.gui = true
        vb.memory = "#{VMRAM}"
        vb.cpus = "#{VMCPU}"
    end

    config.vm.define "hexiwear" do |machine|

        machine.vm.hostname = 'hexiwear'

        # Install SW
        machine.vm.provision "shell", inline: $script_installsw

        # Zephyr
        machine.vm.provision "shell", inline: $script_installz, privileged: false

	# configure ser2net
        machine.vm.provision "shell", inline: $script_configser2net
    end

    config.vm.synced_folder "#{SF}", "/home/vagrant/workspace"

end

